[package]
name = "compress_file"
version = "0.1.0"
edition = "2021"
author = "Christian Brewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.24"
